name: ReviewCode

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [master, main]
    types: [opened, edited, reopened, synchronize]
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
      
jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # interesting alternative: https://github.com/cocogitto/cocogitto
      - uses: webiny/action-conventional-commits@v1.1.0

      - name: Extra conventional commits check
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|test|docs|chore|style|refactor|ci|cd):'
          error: 'You need to start with a conventional commits action.'

      - name: Check Card# reference
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '#\d{4}$'
          flags: 'gm'
          error: 'Your commit message has to end with a card number like "#1234".'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
      
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{0,50}$'
          error: 'The maximum line length of 50 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

      - name: Check Body Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{0,72}$'
          error: 'The maximum line length of 72 characters is exceeded in the body.'
          excludeDescription: 'false' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

      - name: Checkout Policy Library
        uses: actions/checkout@v3
        with:
          repository: reposaur/policy

      #- name: Setup Reposaur
      #  uses: reposaur/repo-audit-action@main

      #- name: Execute Policies
      #  run: |
      #    echo "${{ github.event }}" \
      #    | jq -r '.pull_request' \
      #    | rsr exec > report.sarif
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}

      #- name: Upload Report
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: report.sarif
      #    category: reposaur