name: AuditAndLint

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
    - master
    - main

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Policy Library
        uses: actions/checkout@v2
        with:
          repository: reposaur/policy

#      - name: Setup Reposaur
#        uses: reposaur/repo-audit-action@main

#      - name: Execute Policies
#        run: |
#          echo "${{ github.event }}" \
#          | jq -r '.pull_request' \
#          | rsr exec > report.sarif
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#
#      - name: Upload Report
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: report.sarif
#          category: reposaur

  release:
    uses: ./.github/workflows/release.yaml
    needs: audit
    secrets: inherit
