name: HelmStagingDeploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2.7.0

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Add LinkORB Helm repo
      run: helm repo add linkorb https://charts.linkorb.com

    - name: Update Helm repos
      run: helm repo update

    - name: Create kube dir for credentials
      run: mkdir -p $HOME/.kube

    - name: Save k8s credentials
      run: echo "${{ secrets.K8SSTAGINGCERT }}" | base64 -d > $HOME/.kube/config

    - name: Deploy new version
      run: helm upgrade -f helm-chart/values.test.yaml linkorb linkorb/${{ env.CI_REPOSITORY_NAME }} -n ${{ env.CI_REPOSITORY_NAME }}

    - name: Shred k3s credentials
      run: shred $HOME/.kube/config
