name: HelmPublish
# this publishes the Helm chart to the Chart Museum
# in the future this should also update Chart versions
# this workflow should only be called when a release/tag has been created

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2.7.0

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Update app verion in Chart.yaml
      run: TAG=`git tag | tail -n1` && sed -i -e "s/version.*/version\:\ "${TAG:1}"/g" helm-chart/Chart.yaml

    - name: Update chart verion in Chart.yaml
      run: TAG=`git tag | tail -n1` && sed -i -e "s/.*appVersion.*/appVersion\:\ "${TAG:1}"/g" helm-chart/Chart.yaml

    #TODO: commit changes to Chart.yaml??

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Add Bitnami Helm repo
      run: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update Helm repos
      run: helm repo update

    - name: Install dependencies for Helm chart
      run: cd helm-chart && helm dependency update

    - name: Package Helm chart
      run: helm package helm-chart/

    - name: Upload packaged Helm chart to Museum
      run: curl -u "github:${{ secrets.CHARTMUSEUMPASS }}" --data-binary "@`ls -1 *.tgz | head -n1`" https://charts.linkorb.com/api/charts

  deploy-test:
    uses: ./.github/workflows/deploy-test.yaml
    needs: publish
    secrets: inherit

  deploy-prod:
    uses: ./.github/workflows/deploy-prod.yaml
    needs: publish
    secrets: inherit

